
import "./globals.css";
import Footer from "./pages/Footer";


export const metadata = {
  title: "ਸਿੰਘ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
