
import "./globals.css";
import Footer from "./pages/Footer";
import Navbar from "./pages/Navbar";


export const metadata = {
  title: "Abhishek Singh - Web developer and Photographer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
